USE [master]
GO
/****** Object:  Database [AppLog]    Script Date: 7/13/2025 5:25:37 PM ******/
CREATE DATABASE [AppLog]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppLog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AppLog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AppLog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AppLog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AppLog] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppLog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AppLog] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AppLog] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AppLog] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AppLog] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AppLog] SET ARITHABORT OFF 
GO
ALTER DATABASE [AppLog] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AppLog] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AppLog] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AppLog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AppLog] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AppLog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AppLog] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AppLog] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AppLog] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AppLog] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AppLog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AppLog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AppLog] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AppLog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AppLog] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AppLog] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AppLog] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AppLog] SET RECOVERY FULL 
GO
ALTER DATABASE [AppLog] SET  MULTI_USER 
GO
ALTER DATABASE [AppLog] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AppLog] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AppLog] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AppLog] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AppLog] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AppLog] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AppLog', N'ON'
GO
ALTER DATABASE [AppLog] SET QUERY_STORE = ON
GO
ALTER DATABASE [AppLog] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AppLog]
GO
/****** Object:  Schema [Log]    Script Date: 7/13/2025 5:25:38 PM ******/
CREATE SCHEMA [Log]
GO
/****** Object:  Table [dbo].[Homes]    Script Date: 7/13/2025 5:25:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Homes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Address] [nvarchar](255) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Log].[ApplicationLogs]    Script Date: 7/13/2025 5:25:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Log].[ApplicationLogs](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MethodName] [nvarchar](200) NOT NULL,
	[LogMessage] [nvarchar](max) NOT NULL,
	[ExtraInformation] [nvarchar](max) NULL,
	[LogType] [int] NOT NULL,
	[Status] [int] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[LastUpdatedBy] [int] NULL,
	[LastUpdatedAt] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Homes] ON 
GO
INSERT [dbo].[Homes] ([Id], [Title], [Address], [CreatedDate]) VALUES (1, N'string1', N'string1', CAST(N'2025-07-13T08:25:11.160' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Homes] OFF
GO
ALTER TABLE [Log].[ApplicationLogs] ADD  DEFAULT ((1)) FOR [Status]
GO
ALTER TABLE [Log].[ApplicationLogs] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
/****** Object:  StoredProcedure [Log].[InsertApplicationLog]    Script Date: 7/13/2025 5:25:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Log].[InsertApplicationLog]
    @MethodName NVARCHAR(200),
    @LogMessage NVARCHAR(MAX),
    @ExtraInformation NVARCHAR(MAX) = NULL,
    @LogType INT,
    @CreatedBy INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO [Log].[ApplicationLogs]
    (
        MethodName,
        LogMessage,
        ExtraInformation,
        LogType,
        CreatedBy,
        CreatedAt,
        [Status]
    )
    VALUES
    (
        @MethodName,
        @LogMessage,
        @ExtraInformation,
        @LogType,
        @CreatedBy,
        SYSUTCDATETIME(),
        1
    );
END
GO
USE [master]
GO
ALTER DATABASE [AppLog] SET  READ_WRITE 
GO
